{{- if eq .Values.global.deploymentMode "development" }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.image.kafkadrop.name }}-svc"
  labels:
    app.kubernetes.io/name: {{ .Values.image.kafkadrop.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{ if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {}
  {{ end }}
  selector:
    app.kubernetes.io/name: {{ .Values.image.kafkadrop.name }}
{{- end }}