replicaCount: 1

kafkadrop:
  brokerConnect: kafka-cluster-kafka-bootstrap
  port: 9092
  properties: ""
  truststore: ""
  keystore: ""
  propertiesFile: "kafka.properties"
  truststoreFile: "kafka.truststore.jks"
  keystoreFile: "kafka.keystore.jks"

jvm:
  opts: ""
jmx:
  port: 8686
host:

server:
  port: 9000
  servlet:
    contextPath: /
cmdArgs: ""
nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

mountProtoDesc:
  enabled: false
  hostPath:

service:
  annotations: {}
  type: NodePort
  port: 9000

watchNamespaces: []
watchAnyNamespace: false

image:
  kafkadrop:
    name: kafka-ui
    repository: obsidiandynamics/kafdrop
    tag: latest