apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: audit-events
  labels:
    strimzi.io/cluster: {{ .Values.cluster.name }}
spec:
  config: {}
  partitions: 15
  replicas: 3
  topicName: audit-events