apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  creationTimestamp: '2021-04-16T18:12:13Z'
  generation: 4
  labels:
    strimzi.io/cluster: kafka-connect-cluster
  name: audits
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  config:
    value.converter.schema.registry.url: 'http://kafka-schema-registry:8081'
    value.converter: io.confluent.connect.avro.AvroConverter
    topics: audit-events
    name: audits
    connection.password: '${file:/opt/kafka/external-configuration/connector-config/connector.properties:dbPassword}'
    connector.class: io.confluent.connect.jdbc.JdbcSinkConnector
    table.name.format: audit_event
    connection.user: '${file:/opt/kafka/external-configuration/connector-config/connector.properties:dbUsername}'
    auto.evolve: 'true'
    connection.url: 'jdbc:postgresql://citus-master:5432/${file:/opt/kafka/external-configuration/connector-config/connector.properties:dbName}'
  tasksMax: 1
