apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.cluster.name }}
spec:
  kafka:
    template:
      {{- if .Values.global.registry.kafkaClusterKafka.container.envVars }}
      kafkaContainer:
        env:
        {{- range $name, $value := .Values.global.registry.kafkaClusterKafka.container.envVars }}
        - name: {{ $name }}
          value: {{ $value | quote }}
        {{- end }}{{- end }}
      pod:
        metadata:
          annotations:
            backup.velero.io/backup-volumes: data-0
          labels:
            collect.logs: "plain-text"
        securityContext: {}
      podDisruptionBudget:
        maxUnavailable: 0
    version: 3.0.0
    replicas: {{ .Values.global.registry.kafkaClusterKafka.replicas }}
    {{- if .Values.global.container.requestsLimitsEnabled }}
    resources: {{- toYaml .Values.global.registry.kafkaClusterKafka.container.resources | nindent 6 }}
    {{- end }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
    config:
      transaction.state.log.replication.factor: {{ .Values.global.registry.kafkaClusterKafka.replicas }}
      log.message.format.version: '3.0'
    {{- $logminisr := .Values.global.registry.kafkaClusterKafka.replicas | int -}}
    {{- if lt $logminisr 2 }}
      transaction.state.log.min.isr: {{ .Values.global.registry.kafkaClusterKafka.replicas }}
    {{ else }}
      transaction.state.log.min.isr: {{ sub .Values.global.registry.kafkaClusterKafka.replicas 1 }}
    {{- end }}
      offsets.topic.replication.factor: {{ .Values.global.kafkaOperator.replicationFactor }}
    jvmOptions:
      "-XX":
        "UseG1GC": true
        "MaxGCPauseMillis": 20
        "InitiatingHeapOccupancyPercent": 35
        "ExplicitGCInvokesConcurrent": true
        "MetaspaceSize": "96m"
        "MinMetaspaceFreeRatio": 50
        "MaxMetaspaceFreeRatio": 80
        "G1HeapRegionSize": "16M"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 20Gi
          deleteClaim: false
          class: {{ .Values.storageClass }}
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    logging:
      loggers:
        log4j.logger.kafka.network.Processor: {{ .Values.kafka.logLevel }}
        log4j.logger.org.apache.zookeeper: {{ .Values.kafka.logLevel }}
        log4j.logger.kafka.request.logger: {{ .Values.kafka.logLevel }}
        log4j.logger.kafka.authorizer.logger: {{ .Values.kafka.logLevel }}
        log4j.logger.org.I0Itec.zkclient.ZkClient: {{ .Values.kafka.logLevel }}
        log4j.logger.kafka.server.KafkaApis: {{ .Values.kafka.logLevel }}
        log4j.logger.state.change.logger: {{ .Values.kafka.logLevel }}
        log4j.logger.kafka.log.LogCleaner: {{ .Values.kafka.logLevel }}
        log4j.logger.kafka.controller: {{ .Values.kafka.logLevel }}
        log4j.logger.org.apache.kafka: {{ .Values.kafka.logLevel }}
        log4j.logger.kafka: {{ .Values.kafka.logLevel }}
      type: inline
  kafkaExporter:
    {{- if .Values.global.container.requestsLimitsEnabled }}
    resources: {{- toYaml .Values.global.registry.kafkaClusterKafkaExporter.container.resources | nindent 6 }}
    {{- end }}
    template:
      pod:
        metadata:
          labels:
            collect.logs: "plain-text"
    groupRegex: ".*"
    topicRegex: ".*"
  zookeeper:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper-metrics-config.yml
          name: zookeeper-metrics-config
    {{- if .Values.global.container.requestsLimitsEnabled }}
    resources: {{- toYaml .Values.global.registry.kafkaClusterZookeper.container.resources | nindent 6 }}
    {{- end }}
    logging:
      loggers:
        zookeeper.root.logger: {{ .Values.kafka.logLevel }}
      type: inline
    template:
      {{- if .Values.global.registry.kafkaClusterZookeper.container.envVars }}
      zookeeperContainer:
        env:
        {{- range $name, $value := .Values.global.registry.kafkaClusterZookeper.container.envVars }}
          - name: {{ $name }}
            value: {{ $value | quote }}
        {{- end }}{{- end }}
      pod:
        metadata:
          annotations:
            backup.velero.io/backup-volumes: data
          labels:
            collect.logs: "plain-text"
        securityContext: {}
      podDisruptionBudget:
        maxUnavailable: 0
    replicas: {{ .Values.global.registry.kafkaClusterZookeper.replicas }}
    storage:
      class: {{ .Values.storageClass }}
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
  entityOperator:
    template:
      pod:
        metadata:
          labels:
            collect.logs: "plain-text"
    topicOperator:
    {{- if .Values.global.container.requestsLimitsEnabled }}
      resources: {{- toYaml .Values.global.registry.kafkaClusterEntityOperator.container.resources | nindent 8 }}
    {{- end }}
      logging:
        loggers:
          rootLogger.level: {{ .Values.kafka.logLevel }}
        type: inline
    userOperator:
    {{- if .Values.global.container.requestsLimitsEnabled }}
      resources: {{- toYaml .Values.global.registry.kafkaClusterEntityOperator.container.resources | nindent 8 }}
    {{- end }}
      logging:
        loggers:
          rootLogger.level: {{ .Values.kafka.logLevel }}
        type: inline
