apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: {{ .Values.cluster.name }}
spec:
  kafka:
    template:
      pod:
        metadata:
          annotations:
            backup.velero.io/backup-volumes: data-0
            sidecar.istio.io/inject: "false"
        securityContext: {}
    version: 2.6.0
    replicas: 3
    resources:
      limits:
        cpu: '2'
        memory: 4Gi
      requests:
        cpu: '1'
        memory: 2Gi
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
    config:
      transaction.state.log.replication.factor: 3
      log.message.format.version: '2.6'
      transaction.state.log.min.isr: 2
      offsets.topic.replication.factor: 3
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
        class: {{ .Values.storageClass }}
    metrics: {}
  kafkaExporter:
    groupRegex: ".*"
    topicRegex: ".*"
  zookeeper:
    template:
      pod:
        metadata:
          annotations:
            backup.velero.io/backup-volumes: data
            sidecar.istio.io/inject: "false"
        securityContext: {}
    replicas: 3
    resources:
      limits:
        cpu: '1'
        memory: "1Gi"
      requests:
        cpu: '0.5'
        memory: "0.5Gi"
    storage:
      class: {{ .Values.storageClass }}
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}