apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: {{ .Values.cluster.name }}
spec:
  kafka:
    template:
      pod:
        metadata:
          annotations:
            backup.velero.io/backup-volumes: data-0
            sidecar.istio.io/inject: "false"
        securityContext: {}
    version: 2.6.0
    replicas: {{ .Values.cluster.numberOfKafkaBrokers }}
    {{- if not .Values.global.disableRequestsLimits }}
    resources:
      limits:
        cpu: '2'
        memory: 4Gi
      requests:
        cpu: '1'
        memory: 2Gi
    {{- end }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
    config:
      transaction.state.log.replication.factor: {{ .Values.cluster.numberOfKafkaBrokers }}
      log.message.format.version: '2.6'
    {{- $logminisr := .Values.cluster.numberOfKafkaBrokers | int -}}
    {{- if lt $logminisr 2 }}
      transaction.state.log.min.isr: {{ .Values.cluster.numberOfKafkaBrokers }}
    {{ else }}
      transaction.state.log.min.isr: {{ sub .Values.cluster.numberOfKafkaBrokers 1 }}
    {{- end }}
      offsets.topic.replication.factor: {{ .Values.cluster.numberOfKafkaBrokers }}
    jvmOptions:
      "-XX":
        "UseG1GC": true
        "MaxGCPauseMillis": 20
        "InitiatingHeapOccupancyPercent": 35
        "ExplicitGCInvokesConcurrent": true
        "MetaspaceSize": "96m"
        "MinMetaspaceFreeRatio": 50
        "MaxMetaspaceFreeRatio": 80
        "G1HeapRegionSize": "16M"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 20Gi
          deleteClaim: false
          class: {{ .Values.storageClass }}
    metrics:
      lowercaseOutputName: true
      rules:
        - labels:
            clientId: $3
            partition: $5
            topic: $4
          name: kafka_server_$1_$2
          pattern: >-
            kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+),
            partition=(.*)><>Value
          type: GAUGE
        - labels:
            broker: '$4:$5'
            clientId: $3
          name: kafka_server_$1_$2
          pattern: >-
            kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+),
            brokerPort=(.+)><>Value
          type: GAUGE
        - labels:
            cipher: $5
            listener: $2
            networkProcessor: $3
            protocol: $4
          name: kafka_server_$1_connections_tls_info
          pattern: >-
            kafka.server<type=(.+), cipher=(.+), protocol=(.+), listener=(.+),
            networkProcessor=(.+)><>connections
          type: GAUGE
        - labels:
            clientSoftwareName: $2
            clientSoftwareVersion: $3
            listener: $4
            networkProcessor: $5
          name: kafka_server_$1_connections_software
          pattern: >-
            kafka.server<type=(.+), clientSoftwareName=(.+),
            clientSoftwareVersion=(.+), listener=(.+),
            networkProcessor=(.+)><>connections
          type: GAUGE
        - labels:
            listener: $2
            networkProcessor: $3
          name: kafka_server_$1_$4
          pattern: 'kafka.server<type=(.+), listener=(.+), networkProcessor=(.+)><>(.+):'
          type: GAUGE
        - labels:
            listener: $2
            networkProcessor: $3
          name: kafka_server_$1_$4
          pattern: 'kafka.server<type=(.+), listener=(.+), networkProcessor=(.+)><>(.+)'
          type: GAUGE
        - name: kafka_$1_$2_$3_percent
          pattern: 'kafka.(\w+)<type=(.+), name=(.+)Percent\w*><>MeanRate'
          type: GAUGE
        - name: kafka_$1_$2_$3_percent
          pattern: 'kafka.(\w+)<type=(.+), name=(.+)Percent\w*><>Value'
          type: GAUGE
        - labels:
            $4: $5
          name: kafka_$1_$2_$3_percent
          pattern: 'kafka.(\w+)<type=(.+), name=(.+)Percent\w*, (.+)=(.+)><>Value'
          type: GAUGE
        - labels:
            $4: $5
            $6: $7
          name: kafka_$1_$2_$3_total
          pattern: >-
            kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+),
            (.+)=(.+)><>Count
          type: COUNTER
        - labels:
            $4: $5
          name: kafka_$1_$2_$3_total
          pattern: 'kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+)><>Count'
          type: COUNTER
        - name: kafka_$1_$2_$3_total
          pattern: 'kafka.(\w+)<type=(.+), name=(.+)PerSec\w*><>Count'
          type: COUNTER
        - labels:
            $4: $5
            $6: $7
          name: kafka_$1_$2_$3
          pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Value'
          type: GAUGE
        - labels:
            $4: $5
          name: kafka_$1_$2_$3
          pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Value'
          type: GAUGE
        - name: kafka_$1_$2_$3
          pattern: 'kafka.(\w+)<type=(.+), name=(.+)><>Value'
          type: GAUGE
        - labels:
            $4: $5
            $6: $7
          name: kafka_$1_$2_$3_count
          pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Count'
          type: COUNTER
        - labels:
            $4: $5
            $6: $7
            quantile: 0.$8
          name: kafka_$1_$2_$3
          pattern: >-
            kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*),
            (.+)=(.+)><>(\d+)thPercentile
          type: GAUGE
        - labels:
            $4: $5
          name: kafka_$1_$2_$3_count
          pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Count'
          type: COUNTER
        - labels:
            $4: $5
            quantile: 0.$6
          name: kafka_$1_$2_$3
          pattern: 'kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*)><>(\d+)thPercentile'
          type: GAUGE
        - name: kafka_$1_$2_$3_count
          pattern: 'kafka.(\w+)<type=(.+), name=(.+)><>Count'
          type: COUNTER
        - labels:
            quantile: 0.$4
          name: kafka_$1_$2_$3
          pattern: 'kafka.(\w+)<type=(.+), name=(.+)><>(\d+)thPercentile'
          type: GAUGE
  kafkaExporter:
    groupRegex: ".*"
    topicRegex: ".*"
  zookeeper:
    template:
      pod:
        metadata:
          annotations:
            backup.velero.io/backup-volumes: data
            sidecar.istio.io/inject: "false"
        securityContext: {}
    replicas: {{ .Values.cluster.numberOfKafkaBrokers }}
    {{- if not .Values.global.disableRequestsLimits }}
    resources:
      limits:
        cpu: '1'
        memory: "1Gi"
      requests:
        cpu: '0.5'
        memory: "0.5Gi"
    {{- end }}
    storage:
      class: {{ .Values.storageClass }}
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
