apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter-{{ .Values.namespace }}
  namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    path: {{ .Values.monitoring.prometheusScrapePath }}
    scheme: http
    targetPort: {{ .Values.port }}
  jobLabel: {{ .Values.monitoring.jobLabel }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-exporter
