apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  labels:
    app.kubernetes.io/name: kafka-exporter
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
      name: http
      targetPort: {{ .Values.port }}
  selector:
    app.kubernetes.io/name: kafka-exporter
