kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka-register-job-role-{{ .Release.Namespace }}
  namespace: {{ .Values.global.kafkaOperator.kafkaCentralNamespace }}
rules:
  - verbs:
      - get
      - patch
    apiGroups:
      - '*'
    resources:
      - deployments
      - deployments/scale
    resourceNames:
      - strimzi-cluster-operator
  - verbs:
      - get
      - patch
    apiGroups:
      - '*'
    resources:
      - configmaps
    resourceNames:
      - kafka-watched-namaspaces
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka-register-job-rb-{{ .Release.Namespace }}
  namespace: {{ .Values.global.kafkaOperator.kafkaCentralNamespace }}
subjects:
  - kind: ServiceAccount
    name: kafka-registration
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kafka-register-job-role-{{ .Release.Namespace }}